### PR TITLE
Build main functionality

### PR DESCRIPTION
**Pull request by pbkabali**
Add functionality to:
- Have a default project
- Create a project
- Create a to-do
- Show to-do list for a project
- Move to-do to a different project
- Change to-do priority
- Delete to-do

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi team :wave: 

- [x] I am able to create an empty todo, kindly fix that.

- [x] While creating a todo, It would be nice to have a dropdown to choose a project the todo item belongs to.

**That is it, make these changes, then submit another form for a code review**

### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Comment by Laguna1** [comment]
Thanks for the review @uche-inyama. We have worked on the feedback and submitted it for another review.

**Review by MuriloRoque — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @Laguna1 and @pbkabali :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Comment by pbkabali** [comment]
Thank you @MuriloRoque for taking the time to review our project

**Pull request merged**
